version: '3.8'

services:
  nginx-front:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/etc/nginx/logs
      - ./cert:/etc/nginx/cert
    networks:
      - net
    ports:
      - 80:80
    depends_on:
      - frontend
      - flask-frontend

  frontend:
    container_name: frontend
    build: .
    command: npm start
    volumes:
      - ./src:/data/frontend
      - ./node_modules:/data/frontend/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - net

  flask-frontend:
    container_name: flask-frontend
    build: backend
    command: python -m flask run
    volumes:
      - ./backend:/data/backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=0
      - FLASK_RUN_PORT=5000
    networks:
      - net
    depends_on:
      - frontend

networks:
  net:
    driver: bridge
