version: '3.8'

services:
  flaskaled-srv1:
    image: postgres:latest
    container_name: flaskaled-srv1
    ports:
      - "5433:5432"
    volumes:
      - ./backend/init-db1.sql:/docker-entrypoint-initdb.d/init-db1.sql
    environment:
      - POSTGRES_HOST=flaskaled-srv1
      - POSTGRES_PORT=5432
      - POSTGRES_DB=flaskaledDb1
      - POSTGRES_USER=flaskaled1
      - POSTGRES_PASSWORD=aled1
    restart: unless-stopped