version: '3.8'

services:
  flaskaled-srv1:
    image: postgres:latest
    container_name: flaskaled-srv1
    ports:
      - "5433:5432"
    volumes:
      - ./backend/init-db1.sql:/docker-entrypoint-initdb.d/init-db1.sql
    environment:
      - POSTGRES_USER=flaskaled1
      - POSTGRES_PASSWORD=aled1
      - POSTGRES_DB=flaskaledDb1
    restart: unless-stopped

  flaskaled-srv2:
    image: postgres:latest
    container_name: flaskaled-srv2
    ports:
      - "5434:5432"
    volumes:
      - ./backend/init-db2.sql:/docker-entrypoint-initdb.d/init-db2.sql
    environment:
      - POSTGRES_USER=flaskaled2
      - POSTGRES_PASSWORD=aled2
      - POSTGRES_DB=flaskaledDb2
    restart: unless-stopped
#
#  backend:
#    container_name: backend
#    build: ./backend
#    command: node server.js
#    volumes:
#      - ./backend:/data/backend
#    ports:
#      - "5000:5000"
#    depends_on:
#      - flaskaled-srv1
#      - flaskaled-srv2
#    links:
#      - flaskaled-srv1
#      - flaskaled-srv2
#    environment:
#      FLASK_ENV: development
#      FLASK_DEBUG: 1
#      #DATABASE_URL_USERS:
#      #DATABASE_URL_LOGS:
#      #SECRET_KEY:
#      #ALLOW_ORIGIN:
#
#  frontend:
#    container_name: frontend
#    build: ./frontend
#    command: ng serve --host 0.0.0.0
#    volumes:
#      - ./frontend/src:/data/frontend/
#      - ./frontend/node_modules:/data/frontend/node_modules
#    ports:
#      - "4200:4200"
#    depends_on:
#      - backend
#    links:
#      - backend