version: '3.8'

services:
  flaskaled-srv2:
    image: postgres:latest
    container_name: flaskaled-srv2
    ports:
      - "5434:5432"
    volumes:
      - ./backend/init-db2.sql:/docker-entrypoint-initdb.d/init-db2.sql
    environment:
      - POSTGRES_HOST=flaskaled-srv2
      - POSTGRES_PORT=5432
      - POSTGRES_DB=flaskaledDb2
      - POSTGRES_USER=flaskaled2
      - POSTGRES_PASSWORD=aled2
    restart: unless-stopped
