version: '3.8'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    command: npm start
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/data/frontend
      - ./frontend/node_modules:/data/frontend/node_modules
    environment:
      - NODE_ENV=production