version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    command: python -m flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/data/backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL_USERS=postgresql://flaskaled1:aled1@10.1.3.10:5433/flaskaledDb1
      - DATABASE_URL_LOGS=postgresql://flaskaled2:aled2@10.1.4.10:5434/flaskaledDb2
      - ALLOW_ORIGIN=10.1.1.10
      - SECRET_KEY=default_secret_key

  test:
    container_name: test
    build: ./backend
    command: python test.py
    volumes:
      - ./backend:/data/backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=test
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
      - DATABASE_URL_USERS=postgresql://flaskaled1:aled1@10.1.3.10:5433/flaskaledDb1
      - DATABASE_URL_LOGS=postgresql://flaskaled2:aled2@10.1.4.10:5434/flaskaledDb2
      - SECRET_KEY=default_secret_key
