version: '3.8'

services:
  frontend:
    container_name: frontend
    build: .
    command: npm start
    ports:
      - "4200:4200"
    volumes:
      - ./src:/data/frontend
      - ./node_modules:/data/frontend/node_modules
    environment:
      - NODE_ENV=production
