version: '3.8'

services:
  nginx:
      image: nginx:latest
      volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
        - ./logs/nginx:/etc/nginx/logs
        - ./cert:/etc/nginx/cert
      networks:
        - net
      ports:
        - 80:80

  frontend:
    container_name: frontend
    build: .
    command: npm start
    # ports:
    #   - "4200:4200"
    volumes:
      - ./src:/data/frontend
      - ./node_modules:/data/frontend/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - net

networks:
  net:
    driver: bridge
